---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: wordpress

spec:
  clusterIP: None
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
  labels:
    app: wordpress

spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql

    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysqltoor
        - name: MYSQL_DATABASE
          value: wordpressdb
        - name: MYSQL_USER
          value: wpuser
        - name: MYSQL_PASSWORD
          value: userwp

        ports:
        - containerPort: 3306
          name: mysql

        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-vol
---